name: Integration Stage Pipeline

on:
  push:
    branches:
      - develop

jobs:
  super.lint:
    name: Lint code base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Production Stage Pipeline
        uses: github/super-linter@v3
        env:
          DEFAULT_BRANCH: develop
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  build:
   runs-on: ubuntu-latest
   steps:
     - name: Setup Python
       uses: actions/setup-python@v2.2.2
     - name: Install dependencies
       run: |
           python -m pip install --upgrade pip
           pip install flake8
           if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
           pip install -e.
     - run: |
         touch test.txt
     - name: Upload package
       uses: actions/upload-artifact@v2
       with:
         name: dev-package
         path: test.txt

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: run linter [flake8]
        run: flake8.
  test:
    runs-on: ubuntu-latest
    steps:
      - name: run unit tests [pytest]
        run: pytest
  deploy:
    needs: [build, lint, test]
    runs-on: ubuntu-latest
    steps:
      - name: Download package
        uses: actions/download-artifact@v2
        with:
          name: dev-package
          path: ~/distribution
      - uses: actions/checkout@v1
      - run: cat ~/distribution/test.txt
